src/lists/urls.py
from django.conf.urls import url
from lists.views import (
	ShoppingListView,
	ShoppingDetailView,
	ShoppingCreateView,
	ShoppingUpdateView
	)

urlpatterns = [

    url(r'^$',ShoppingListView.as_view(),name='lists'),
    url(r'^create/$',ShoppingCreateView.as_view(),name='create'),
    url(r'^(?P<slug>[\w-]+)/$',ShoppingUpdateView.as_view(),name='list-detail'),
    
    
]

src/profiles/urls.py
from django.conf.urls import url
from profiles.views import ProfileDetailView

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$',ProfileDetailView.as_view(),name='profile'),    
]

src/shoplist/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,PasswordChangeView,LogoutView
from django.contrib.auth import views as auth_views
from lists.views import HomeListView
from profiles.views import RegisterView


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^recent/$',HomeListView.as_view(),name='recent'),
    url(r'^lists/', include('lists.urls')),
    url(r'^u/', include('profiles.urls')),
    url(r'^login/$',LoginView.as_view(),name='login'),
     url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^password_reset/$',PasswordChangeView.as_view(),name='password_reset'),
    url(r'^$',TemplateView.as_view(template_name='home.html'),name='home'),
    url(r'^contact$',TemplateView.as_view(template_name='contact.html'),name='contact'),

]

src/lists/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save,post_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator

User 	= settings.AUTH_USER_MODEL

class Shopping(models.Model):
	owner 		= models.ForeignKey(User)
	name		= models.CharField(max_length=200,null=True,blank=True)
	category	= models.CharField(max_length=200,null=True,blank=True) 
	content		= models.TextField(help_text='seperate with commas', null=False, blank=False)
	timestamp	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)
	slug		= models.SlugField(null=True,blank=True)
	public 		= models.BooleanField(default=True)

	class Meta:
		ordering =['-updated', '-timestamp']


	def __str__(self):
		return self.name

	def get_content(self):
		return self.content.split(",")

		
	def get_absolute_url(self):
		return reverse('list-detail', kwargs={'slug':self.slug})

	@property
	def title(self):
		return self.name

def s_pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)




pre_save.connect(s_pre_save_receiver, sender=Shopping)

src/profiles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


User = settings.AUTH_USER_MODEL

class Profile(models.Model):
	user 			= models.OneToOneField(User)
	activated 		= models.BooleanField(default=True)
	timestamp		= models.DateTimeField(auto_now_add=True)
	updated			= models.DateTimeField(auto_now=True)


	def __str__(self):
		return self.user.username

src/lists/forms.py
from django import forms
from django.forms import ModelForm
from .models import Shopping

class ShoppingCreateForm(forms.Form):
	name		= forms.CharField(required=False)
	category	= forms.CharField(required=True)
	content		= forms.CharField(required=True)


class ShoppingListCreateForm(ModelForm):

	class Meta:
		model 	= Shopping
		fields	= ['name', 'category', 'content', 'public', 'slug'] 

src/profiles/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

User    = get_user_model()

class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_email(self):
        email   = self.cleaned_data.get('email')
        qs      = User.objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError('That email is already in use')
        return email


    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        # create a new user hash for activating email.

        if commit:
            user.save()
        return user

src/lists/views.py
from __future__ import unicode_literals
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.views.generic import View,ListView,DetailView,CreateView,UpdateView
from .models import Shopping
from .forms import ShoppingListCreateForm



class HomeListView(LoginRequiredMixin, ListView):
	template_name = 'lists/shopping_list.html'
	def get_queryset(self):
		slug = self.kwargs.get('slug')
		if slug:
			queryset 	= Shopping.objects.filter(
					Q(category__icontains=slug) |
					Q(category__iexact=slug)
				)
		else:
			queryset 	= Shopping.objects.all()
		return queryset


class ShoppingListView(LoginRequiredMixin, ListView):
	template_name = 'profiles/user-detail.html'
	def get_queryset(self):
		return Shopping.objects.filter(owner=self.request.user)

class ShoppingDetailView(LoginRequiredMixin, DetailView):
	def get_queryset(self):
		return Shopping.objects.filter(owner=self.request.user)

class ShoppingCreateView(LoginRequiredMixin, CreateView):
	form_class 		=  ShoppingListCreateForm
	template_name 	=  'form.html'
	def form_valid(self, form):
		instance 		= form.save(commit=False)
		instance.owner 	= self.request.user
		return super (ShoppingCreateView, self).form_valid(form)

	def get_context_data(self, *args, **kwargs):
		context 			= super(ShoppingCreateView, self).get_context_data(*args, **kwargs)
		context['title'] 	= 'AddList'
		return context



class ShoppingUpdateView(LoginRequiredMixin, UpdateView):
	form_class 		= ShoppingListCreateForm
	template_name 	= 'lists/detail-update.html'

	def get_queryset(self):
		return Shopping.objects.filter(owner=self.request.user)

	def form_valid(self, form):
		instance 		= form.save(commit=False)
		instance.owner 	= self.request.user
		return super (ShoppingUpdateView, self).form_valid(form)


	def get_context_data(self, *args, **kwargs):
		context 			= super(ShoppingUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] 	= 'ListUpdate'
		return context


	

src/profiles/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import get_user_model
from django.http import Http404

from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import DetailView,CreateView
from .forms import RegisterForm
User 	= get_user_model()

class ProfileDetailView(DetailView):
	template_name = 'profiles/user-detail.html'
	queryset 	  =  User.objects.filter(is_active=True)

	def get_object(self):
		username = self.kwargs.get('username')
		if username is None:
			raise Http404
		return get_object_or_404(User, username__iexact=username, is_active=True)


class RegisterView(CreateView):
	form_class 		= RegisterForm
	template_name 	= 'registration/register.html'
	success_url 	= '/login'


	def dispatch(self, *args, **kwargs):
		return super (RegisterView, self).dispatch(*args, **kwargs)

src/profiles/templates/profiles/user-detail.html
{% extends 'base.html' %}
{% block title %}{{ user.username }}|| {{block.super}} {% endblock %}

{% block content %}

<h1>{{ user.username }}</h1>
<hr>
<h4>
	<a href="{% url 'create' %}">
		<button class="ui button">
				AddShopList
		</button>
	</a>
</h4>
{% for shop in user.shopping_set.all %}
			<div class="thumbnail">
				<b>{{shop.title}}</b>
				
				<ul>
				<a href="{{ shop.get_absolute_url}}">{{shop.category}}</a><br>
				{% for item in shop.get_content %}
	
				<span style="border-radius: 5px; background-color: #ccc;margin-right: 4px;padding: 2px 4px;">
				{{item}}
				</span>
	
			
				{% endfor %}
				</ul>

			</div>
	

{% endfor %}

{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} shoplist.com {% endblock %} </title>
	{% include 'snippets/css.html' %}
</head>
<body>


<div class="container">
   <div class="row">
			<div class="col-sm-6 text-center col-sm-offset-3">
				
	            	<h2>shoplist.com</h2>
	    			{% include 'snippets/nav.html' %}

					{% block content %}
				
		
					{% endblock %}
					{% include 'snippets/js.html' %}
             
        	</div>
    </div>
 </div>

		
</body>
</html>

src/templates/contact.html
{% extends 'base.html' %}

{% block title %} contact || {{block.super}} {% endblock %}

{% block content %}

<h1>contact me</h1>
<button class="ui button">
  				Zeus
</button>

{% endblock %}

src/templates/form.html
{% extends 'base.html' %}
{% block title %}{{ title }} || {{block.super}} {% endblock %}

{% block content %}
<h3> {{ title }} </h3>

{% include 'snippets/snipp-form.html' %}

{% endblock content %}

src/templates/home.html
{% extends 'base.html' %}
{% block title %}{{block.super}} {% endblock %}

{% block content %}
	<h2>welcome to shoplist.com</h2>
	{% if request.user.is_authenticated %}
	<h5>You made it</h5>
	{% else %}
	<b>please login/register to see shoplists.</b>
	{% endif %}
	
{% endblock content %}

src/templates/lists/detail-update.html
{% extends 'base.html' %}
{% block title %} detail-update || {{block.super}} {% endblock %}

{% block content %}<br>
<h3> {{form.instance.name}}<small>{{form.instance.category}}</small></h3>
	
	<p>{{form.instance.content}}</p>
	<p>by {{form.instance.owner}} on {{form.instance.timestamp}}<br> updated {{form.instance.updated | timesince}} ago</p>
<hr>
<h2>Make changes</h2>

{% include 'snippets/snipp-form.html' with form=form %}


{% endblock content %}

src/templates/lists/shopping_detail.html
{% extends 'base.html' %}
{% block title %} detail || {{block.super}} {% endblock %}

{% block content %}
<h3>{{object.name}}<a href="{{ shop.get_absolute_url}}"><small>{{object.category}}</small></a></h3>
<p>{{object.content}}</p>
<p>by {{object.owner}} on {{object.timestamp}}<br> updated {{object.updated | timesince}} ago</p>
{% endblock content %}

src/templates/lists/shopping_list.html
{% extends 'base.html' %}
{% block title %} {{ object.title }} {{block.super}} {% endblock %}

{% block content %}

<h4><a href="{% url 'create' %}">
	<button class="ui button">
  				AddShopList
	</button>
</a>
</h4>
	{% for obj in object_list %}
				<div class="thumbnail">
					<b>{{obj.name}}</b>
					<ul>
						<p>{{obj.category}}</p>
						<span style="border-radius: 5px; background-color: #ccc;margin-right: 4px;padding: 2px 4px;">
							{{obj.content}}
						</span><br>
						on {{obj.timestamp}} by {{obj.owner}}
					</ul>
				</div>
			
	{% endfor %}
	
{% endblock %}

src/templates/snippets/css.html
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

src/templates/snippets/js.html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script src=" http://code.jquery.com/jquery-3.2.1.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

src/templates/snippets/nav.html
<a href="{% url 'home' %}">Home</a>
{% if request.user.is_authenticated %}
<a href="{% url 'lists' %}">mylists</a>
<a href="{% url 'recent' %}">recent</a>
<a href='{% url "logout" %}'>Logout</a>
{% else %}
<a href='{% url "register" %}'>Register</a>
<a href='{% url "login" %}'>Login</a>
<a href="{% url 'contact' %}">contact</a>
{% endif %}

src/templates/snippets/snipp-form.html
<form method="POST">{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">save</button>
</form>